### ISSUE TITLE
chore: Docker Compose上でサインインが動作しない

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#118]
Docker Composeで起動したフロントエンドでサインインが正常に動作していない。サインイン、サインアップには成功したと表示されるが、UIがサインイン済みのものに変化しない。

see also #52

**Comment by rdrgn** [comment]
https://shitforces.herokuapp.com/ は正常に動作しているので、Docker Composeで起動する開発環境のみでの問題だと思われます。

**Comment by rdrgn** [comment]
読む。
[Kotlin × Spring Securityを使用したRESTfulな認証機構の実装 – てっくぼっと！](https://blog.applibot.co.jp/2017/11/08/spring-security-with-kotlin/)

**Comment by rdrgn** [comment]
サインインするときにCookieが保存されていないように見える。

`locahost:3000`（フロントエンド）と`localhost:8080`（バックエンド）というように、ポートが違うとだめなのかと思ったけれど、Cookieにポート番号は関係ないらしい。
[security - Are HTTP cookies port specific? - Stack Overflow](https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific)

**Comment by rdrgn** [comment]
関係があるかも。
[CORSリクエストでクレデンシャル(≒クッキー)を必要とする場合の注意点 - Qiita](https://qiita.com/kawaz/items/1e51c374b7a13c21b7e2)

**Comment by rdrgn** [comment]
> 資格情報を含むリクエストに対するレスポンスの時、サーバーは Access-Control-Allow-Origin ヘッダーで "*" ワイルドカードではなくオリジンを指定しなければなりません。

[オリジン間リソース共有 (CORS) - HTTP | MDN](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS)

**Comment by rdrgn** [comment]
`@CrossOrigin`
[Spring CORS - @CrossOrigin and CorsRegistry - HowToDoInJava](https://howtodoinjava.com/spring5/webmvc/spring-mvc-cors-configuration/)

**Comment by rdrgn** [comment]
今回は採用しないけれど、バックエンドとフロントエンドを別々に動かすのをやめることでも解決できる。

`docker-compose.yml`
```
version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: shop_one
  app:
    image: shitforces_app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/frontend/node_modules
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/db"
      DATABASE_PASSWORD: password
      DATABASE_USER: shop_one
    command: ./gradlew bootRun
    depends_on:
      - db
volumes:
  postgres-data:
```

`Dockerfile`
```
FROM gradle:jdk11
RUN apt-get update && apt-get install -y curl gnupg
RUN curl -fsSL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get update && apt-get install -y nodejs
RUN npm install npm@latest -g
WORKDIR /app
```
